image: python:3

lint:
 stage: build
 script:
 - pip install yapf
 - yapf --recursive --style google .
 only:
 - pushes

unittest:
 stage: test
 script:
  - pip install -r 'requirements.txt'
  - pytest
 only:
  - pushes
