image: python:3

lint:
 stage: build
 script:
 - pip install yapf
 - yapf --recursive --style google .
 only:
 - pushes

unittest:
 stage: test
 needs:
  - pipeline: test
    job: lint
 script:
  - pip install -r 'requirements.txt'
  - pip list
  - pytest
 only:
  - pushes

deployment:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 only:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - gcloud app deploy --quiet --project snappy-premise-377919